import bcrypt from 'bcryptjs';
import { IRoad, IJunction, ITrafficDataPoint, IAlert, IRouteAlternative, IUser } from '../types';

const defaultSeedPasswordHash = bcrypt.hashSync('Admin@123!', 10);

export const initialUsers: IUser[] = [
  {
    id: 'usr-1',
    name: 'Dr. Rajesh Sharma (IAS)',
    email: 'commissioner@nmcnagpur.gov.in',
    passwordHash: defaultSeedPasswordHash,
    role: 'Planning Authority',
    agency: 'Nagpur Municipal Corporation (NMC) & NIT',
    createdAt: new Date('2026-01-15'),
  },
  {
    id: 'usr-2',
    name: 'DCP Sandeep Patil (IPS)',
    email: 'traffic.cp@nagpurpolice.gov.in',
    passwordHash: defaultSeedPasswordHash,
    role: 'Traffic Administrator',
    agency: 'Nagpur City Traffic Police Command',
    createdAt: new Date('2026-02-01'),
  },
  {
    id: 'usr-3',
    name: 'Ananya Deshmukh',
    email: 'mobility.analyst@nsscdcl.in',
    passwordHash: defaultSeedPasswordHash,
    role: 'Analyst',
    agency: 'Nagpur Smart and Sustainable City Development Corp (NSSCDCL)',
    createdAt: new Date('2026-02-20'),
  },
];

export const initialJunctions: IJunction[] = [
  {
    id: 'J1',
    name: 'Variety Square (Sitabuldi)',
    code: 'J-VAR-01',
    location: { lat: 21.1460, lng: 79.0815 },
    zone: 'Zone A - Sitabuldi & Central Commercial',
    incomingRoadIds: ['R1', 'R2', 'R7', 'R15'],
    vehicleCount: 2680,
    queueLengthVeh: 95,
    averageWaitingTimeSec: 84,
    congestionLevel: 'severe',
    signalCycleSec: 130,
    greenDurationSec: 40,
    yellowDurationSec: 5,
    redDurationSec: 85,
    currentPhase: 'green',
    isAdaptive: false,
  },
  {
    id: 'J2',
    name: 'RBI Square (Zero Mile Heritage)',
    code: 'J-RBI-02',
    location: { lat: 21.1498, lng: 79.0832 },
    zone: 'Zone A - Sitabuldi & Central Commercial',
    incomingRoadIds: ['R1', 'R2', 'R16', 'R22'],
    vehicleCount: 2950,
    queueLengthVeh: 115,
    averageWaitingTimeSec: 98,
    congestionLevel: 'severe',
    signalCycleSec: 135,
    greenDurationSec: 45,
    yellowDurationSec: 5,
    redDurationSec: 85,
    currentPhase: 'red',
    isAdaptive: false,
  },
  {
    id: 'J3',
    name: 'Lokmat Square (Wardha Road)',
    code: 'J-LOK-03',
    location: { lat: 21.1378, lng: 79.0792 },
    zone: 'Zone B - Wardha Road & MIHAN IT Corridor',
    incomingRoadIds: ['R1', 'R5', 'R14'],
    vehicleCount: 2450,
    queueLengthVeh: 82,
    averageWaitingTimeSec: 72,
    congestionLevel: 'heavy',
    signalCycleSec: 120,
    greenDurationSec: 45,
    yellowDurationSec: 5,
    redDurationSec: 70,
    currentPhase: 'yellow',
    isAdaptive: false,
  },
  {
    id: 'J4',
    name: 'Rahate Colony Square',
    code: 'J-RAH-04',
    location: { lat: 21.1275, lng: 79.0768 },
    zone: 'Zone B - Wardha Road & MIHAN IT Corridor',
    incomingRoadIds: ['R4', 'R13', 'R20'],
    vehicleCount: 1850,
    queueLengthVeh: 52,
    averageWaitingTimeSec: 46,
    congestionLevel: 'moderate',
    signalCycleSec: 100,
    greenDurationSec: 45,
    yellowDurationSec: 5,
    redDurationSec: 50,
    currentPhase: 'green',
    isAdaptive: false,
  },
  {
    id: 'J5',
    name: 'Chhatrapati Square (Wardha Road Flyover)',
    code: 'J-CHT-05',
    location: { lat: 21.1098, lng: 79.0682 },
    zone: 'Zone B - Wardha Road & MIHAN IT Corridor',
    incomingRoadIds: ['R5', 'R10', 'R17'],
    vehicleCount: 3100,
    queueLengthVeh: 120,
    averageWaitingTimeSec: 105,
    congestionLevel: 'severe',
    signalCycleSec: 140,
    greenDurationSec: 45,
    yellowDurationSec: 5,
    redDurationSec: 90,
    currentPhase: 'green',
    isAdaptive: false,
  },
  {
    id: 'J6',
    name: 'Ajni Square (Medical College Link)',
    code: 'J-AJN-06',
    location: { lat: 21.1215, lng: 79.0850 },
    zone: 'Zone D - South-Eastern Arterials (Medical-Umred)',
    incomingRoadIds: ['R9', 'R11', 'R24'],
    vehicleCount: 2540,
    queueLengthVeh: 88,
    averageWaitingTimeSec: 78,
    congestionLevel: 'heavy',
    signalCycleSec: 120,
    greenDurationSec: 40,
    yellowDurationSec: 5,
    redDurationSec: 75,
    currentPhase: 'red',
    isAdaptive: false,
  },
  {
    id: 'J7',
    name: 'Medical Square (Great Nag Road)',
    code: 'J-MED-07',
    location: { lat: 21.1340, lng: 79.0980 },
    zone: 'Zone D - South-Eastern Arterials (Medical-Umred)',
    incomingRoadIds: ['R6', 'R10', 'R19'],
    vehicleCount: 2200,
    queueLengthVeh: 70,
    averageWaitingTimeSec: 64,
    congestionLevel: 'heavy',
    signalCycleSec: 115,
    greenDurationSec: 40,
    yellowDurationSec: 5,
    redDurationSec: 70,
    currentPhase: 'green',
    isAdaptive: false,
  },
  {
    id: 'J8',
    name: 'Sakkardara Square (Umred Road)',
    code: 'J-SAK-08',
    location: { lat: 21.1235, lng: 79.1120 },
    zone: 'Zone D - South-Eastern Arterials (Medical-Umred)',
    incomingRoadIds: ['R6', 'R11', 'R21'],
    vehicleCount: 2750,
    queueLengthVeh: 92,
    averageWaitingTimeSec: 86,
    congestionLevel: 'severe',
    signalCycleSec: 125,
    greenDurationSec: 40,
    yellowDurationSec: 5,
    redDurationSec: 80,
    currentPhase: 'green',
    isAdaptive: false,
  },
  {
    id: 'J9',
    name: 'Telephone Exchange Square (CA Road / Itwari)',
    code: 'J-ITW-09',
    location: { lat: 21.1485, lng: 79.1245 },
    zone: 'Zone A - Sitabuldi & Central Commercial',
    incomingRoadIds: ['R2', 'R8', 'R23'],
    vehicleCount: 2850,
    queueLengthVeh: 105,
    averageWaitingTimeSec: 92,
    congestionLevel: 'severe',
    signalCycleSec: 130,
    greenDurationSec: 40,
    yellowDurationSec: 5,
    redDurationSec: 85,
    currentPhase: 'red',
    isAdaptive: false,
  },
  {
    id: 'J10',
    name: 'Law College Square (Amravati Road)',
    code: 'J-LAW-10',
    location: { lat: 21.1510, lng: 79.0560 },
    zone: 'Zone C - Western Institutional (Amravati-VNIT)',
    incomingRoadIds: ['R7', 'R18', 'R24'],
    vehicleCount: 1950,
    queueLengthVeh: 58,
    averageWaitingTimeSec: 52,
    congestionLevel: 'moderate',
    signalCycleSec: 105,
    greenDurationSec: 45,
    yellowDurationSec: 5,
    redDurationSec: 55,
    currentPhase: 'green',
    isAdaptive: false,
  },
  {
    id: 'J11',
    name: 'Shankar Nagar Square (WHC Road)',
    code: 'J-SHK-11',
    location: { lat: 21.1390, lng: 79.0585 },
    zone: 'Zone C - Western Institutional (Amravati-VNIT)',
    incomingRoadIds: ['R7', 'R12', 'R20'],
    vehicleCount: 2100,
    queueLengthVeh: 66,
    averageWaitingTimeSec: 60,
    congestionLevel: 'heavy',
    signalCycleSec: 110,
    greenDurationSec: 45,
    yellowDurationSec: 5,
    redDurationSec: 60,
    currentPhase: 'green',
    isAdaptive: false,
  },
  {
    id: 'J12',
    name: 'Automotive Square (Kamptee Road)',
    code: 'J-AUT-12',
    location: { lat: 21.1920, lng: 79.1020 },
    zone: 'Zone F - Outer Ring Road & Peripheral Bypass',
    incomingRoadIds: ['R8', 'R22', 'R23'],
    vehicleCount: 1150,
    queueLengthVeh: 22,
    averageWaitingTimeSec: 24,
    congestionLevel: 'low',
    signalCycleSec: 90,
    greenDurationSec: 50,
    yellowDurationSec: 5,
    redDurationSec: 35,
    currentPhase: 'green',
    isAdaptive: false,
  },
];

export const initialRoads: IRoad[] = [
  {
    id: 'R1',
    name: 'Wardha Road Arterial (Variety Sq → Lokmat Sq)',
    code: 'NGP-RD-01',
    zone: 'Zone B',
    zoneName: 'Wardha Road & MIHAN IT Corridor',
    startJunctionId: 'J1',
    endJunctionId: 'J3',
    coordinates: [
      [21.1460, 79.0815],
      [21.1420, 79.0805],
      [21.1378, 79.0792],
    ],
    lengthKm: 2.1,
    lanes: 4,
    speedLimitKmh: 50,
    capacityVehPerHour: 2200,
    currentTrafficVeh: 2130,
    averageSpeedKmh: 13,
    utilizationPct: 97,
    congestionLevel: 'severe',
    estimatedTravelTimeMin: 9.7,
    estimatedDelayMin: 7.2,
    status: 'bottleneck',
  },
  {
    id: 'R2',
    name: 'Central Avenue (CA Road) - Sitabuldi to Itwari',
    code: 'NGP-RD-02',
    zone: 'Zone A',
    zoneName: 'Sitabuldi & Central Commercial',
    startJunctionId: 'J1',
    endJunctionId: 'J9',
    coordinates: [
      [21.1460, 79.0815],
      [21.1480, 79.0950],
      [21.1485, 79.1245],
    ],
    lengthKm: 4.6,
    lanes: 4,
    speedLimitKmh: 45,
    capacityVehPerHour: 2100,
    currentTrafficVeh: 2040,
    averageSpeedKmh: 11,
    utilizationPct: 97,
    congestionLevel: 'severe',
    estimatedTravelTimeMin: 25.1,
    estimatedDelayMin: 19.0,
    status: 'bottleneck',
  },
  {
    id: 'R3',
    name: 'Nagpur Outer Ring Road (Wadi Bypass to Kamptee)',
    code: 'NGP-RD-03',
    zone: 'Zone F',
    zoneName: 'Outer Ring Road & Peripheral Bypass',
    startJunctionId: 'J10',
    endJunctionId: 'J12',
    coordinates: [
      [21.1510, 79.0560],
      [21.1850, 79.0680],
      [21.1920, 79.1020],
    ],
    lengthKm: 7.8,
    lanes: 6,
    speedLimitKmh: 80,
    capacityVehPerHour: 4200,
    currentTrafficVeh: 1650,
    averageSpeedKmh: 64,
    utilizationPct: 39,
    congestionLevel: 'low',
    estimatedTravelTimeMin: 7.3,
    estimatedDelayMin: 0.8,
    isAlternativeRoute: true,
    status: 'underutilized',
  },
  {
    id: 'R4',
    name: 'South Ring Road (Besa - Manewada - Dighori Bypass)',
    code: 'NGP-RD-04',
    zone: 'Zone E',
    zoneName: 'South-West Bypass & Hingna Corridor',
    startJunctionId: 'J4',
    endJunctionId: 'J8',
    coordinates: [
      [21.1275, 79.0768],
      [21.1150, 79.0920],
      [21.1235, 79.1120],
    ],
    lengthKm: 4.8,
    lanes: 6,
    speedLimitKmh: 70,
    capacityVehPerHour: 3600,
    currentTrafficVeh: 1120,
    averageSpeedKmh: 58,
    utilizationPct: 31,
    congestionLevel: 'low',
    estimatedTravelTimeMin: 5.0,
    estimatedDelayMin: 0.5,
    isAlternativeRoute: true,
    status: 'underutilized',
  },
  {
    id: 'R5',
    name: 'Wardha Road Airport Expressway (Lokmat Sq → Chhatrapati Sq)',
    code: 'NGP-RD-05',
    zone: 'Zone B',
    zoneName: 'Wardha Road & MIHAN IT Corridor',
    startJunctionId: 'J3',
    endJunctionId: 'J5',
    coordinates: [
      [21.1378, 79.0792],
      [21.1250, 79.0740],
      [21.1098, 79.0682],
    ],
    lengthKm: 3.4,
    lanes: 4,
    speedLimitKmh: 60,
    capacityVehPerHour: 2400,
    currentTrafficVeh: 2280,
    averageSpeedKmh: 16,
    utilizationPct: 95,
    congestionLevel: 'severe',
    estimatedTravelTimeMin: 12.8,
    estimatedDelayMin: 9.4,
    status: 'bottleneck',
  },
  {
    id: 'R6',
    name: 'Great Nag Road (Baidyanath Sq → Sakkardara Sq)',
    code: 'NGP-RD-06',
    zone: 'Zone D',
    zoneName: 'South-Eastern Arterials (Medical-Umred)',
    startJunctionId: 'J7',
    endJunctionId: 'J8',
    coordinates: [
      [21.1340, 79.0980],
      [21.1290, 79.1050],
      [21.1235, 79.1120],
    ],
    lengthKm: 2.2,
    lanes: 4,
    speedLimitKmh: 45,
    capacityVehPerHour: 1800,
    currentTrafficVeh: 1620,
    averageSpeedKmh: 18,
    utilizationPct: 90,
    congestionLevel: 'heavy',
    estimatedTravelTimeMin: 7.3,
    estimatedDelayMin: 4.4,
    status: 'congested',
  },
  {
    id: 'R7',
    name: 'West High Court (WHC) Road (Law College Sq → Shankar Nagar)',
    code: 'NGP-RD-07',
    zone: 'Zone C',
    zoneName: 'Western Institutional (Amravati-VNIT)',
    startJunctionId: 'J10',
    endJunctionId: 'J11',
    coordinates: [
      [21.1510, 79.0560],
      [21.1450, 79.0570],
      [21.1390, 79.0585],
    ],
    lengthKm: 1.8,
    lanes: 4,
    speedLimitKmh: 45,
    capacityVehPerHour: 1900,
    currentTrafficVeh: 1560,
    averageSpeedKmh: 22,
    utilizationPct: 82,
    congestionLevel: 'heavy',
    estimatedTravelTimeMin: 4.9,
    estimatedDelayMin: 2.5,
    status: 'congested',
  },
  {
    id: 'R8',
    name: 'Kamptee Road National Highway (RBI Sq → Automotive Sq)',
    code: 'NGP-RD-08',
    zone: 'Zone F',
    zoneName: 'Outer Ring Road & Peripheral Bypass',
    startJunctionId: 'J2',
    endJunctionId: 'J12',
    coordinates: [
      [21.1498, 79.0832],
      [21.1700, 79.0920],
      [21.1920, 79.1020],
    ],
    lengthKm: 5.6,
    lanes: 6,
    speedLimitKmh: 65,
    capacityVehPerHour: 3400,
    currentTrafficVeh: 1650,
    averageSpeedKmh: 46,
    utilizationPct: 48,
    congestionLevel: 'low',
    estimatedTravelTimeMin: 7.3,
    estimatedDelayMin: 1.5,
    isAlternativeRoute: true,
    status: 'underutilized',
  },
  {
    id: 'R9',
    name: 'Station Road & Cotton Market Connector',
    code: 'NGP-RD-09',
    zone: 'Zone A',
    zoneName: 'Sitabuldi & Central Commercial',
    startJunctionId: 'J1',
    endJunctionId: 'J6',
    coordinates: [
      [21.1460, 79.0815],
      [21.1350, 79.0840],
      [21.1215, 79.0850],
    ],
    lengthKm: 2.9,
    lanes: 4,
    speedLimitKmh: 45,
    capacityVehPerHour: 1900,
    currentTrafficVeh: 1710,
    averageSpeedKmh: 17,
    utilizationPct: 90,
    congestionLevel: 'heavy',
    estimatedTravelTimeMin: 10.2,
    estimatedDelayMin: 6.3,
    status: 'congested',
  },
  {
    id: 'R10',
    name: 'Medical College Approach Corridor (Ajni Sq → Medical Sq)',
    code: 'NGP-RD-10',
    zone: 'Zone D',
    zoneName: 'South-Eastern Arterials (Medical-Umred)',
    startJunctionId: 'J6',
    endJunctionId: 'J7',
    coordinates: [
      [21.1215, 79.0850],
      [21.1280, 79.0920],
      [21.1340, 79.0980],
    ],
    lengthKm: 2.1,
    lanes: 4,
    speedLimitKmh: 50,
    capacityVehPerHour: 2000,
    currentTrafficVeh: 1300,
    averageSpeedKmh: 34,
    utilizationPct: 65,
    congestionLevel: 'moderate',
    estimatedTravelTimeMin: 3.7,
    estimatedDelayMin: 1.2,
    status: 'normal',
  },
  {
    id: 'R11',
    name: 'Umred Road Arterial (Sakkardara Sq → Dighori Naka)',
    code: 'NGP-RD-11',
    zone: 'Zone D',
    zoneName: 'South-Eastern Arterials (Medical-Umred)',
    startJunctionId: 'J8',
    endJunctionId: 'J4',
    coordinates: [
      [21.1235, 79.1120],
      [21.1150, 79.1250],
      [21.1080, 79.1400],
    ],
    lengthKm: 3.5,
    lanes: 4,
    speedLimitKmh: 50,
    capacityVehPerHour: 2000,
    currentTrafficVeh: 1860,
    averageSpeedKmh: 15,
    utilizationPct: 93,
    congestionLevel: 'severe',
    estimatedTravelTimeMin: 14.0,
    estimatedDelayMin: 9.8,
    status: 'severe' as any,
  },
  {
    id: 'R12',
    name: 'Ambazari Lake Promenade & VNIT Boulevard',
    code: 'NGP-RD-12',
    zone: 'Zone C',
    zoneName: 'Western Institutional (Amravati-VNIT)',
    startJunctionId: 'J11',
    endJunctionId: 'J5',
    coordinates: [
      [21.1390, 79.0585],
      [21.1250, 79.0550],
      [21.1098, 79.0682],
    ],
    lengthKm: 4.1,
    lanes: 4,
    speedLimitKmh: 55,
    capacityVehPerHour: 2200,
    currentTrafficVeh: 1540,
    averageSpeedKmh: 36,
    utilizationPct: 70,
    congestionLevel: 'moderate',
    estimatedTravelTimeMin: 6.8,
    estimatedDelayMin: 2.3,
    status: 'normal',
  },
  {
    id: 'R13',
    name: 'Wadi Bypass Expressway (Amravati Rd Bypass → Hingna)',
    code: 'NGP-RD-13',
    zone: 'Zone E',
    zoneName: 'South-West Bypass & Hingna Corridor',
    startJunctionId: 'J10',
    endJunctionId: 'J4',
    coordinates: [
      [21.1510, 79.0560],
      [21.1350, 79.0350],
      [21.1275, 79.0768],
    ],
    lengthKm: 5.6,
    lanes: 6,
    speedLimitKmh: 75,
    capacityVehPerHour: 3800,
    currentTrafficVeh: 1080,
    averageSpeedKmh: 62,
    utilizationPct: 28,
    congestionLevel: 'low',
    estimatedTravelTimeMin: 5.4,
    estimatedDelayMin: 0.6,
    isAlternativeRoute: true,
    status: 'underutilized',
  },
  {
    id: 'R14',
    name: 'Hingna MIDC Industrial Expressway',
    code: 'NGP-RD-14',
    zone: 'Zone E',
    zoneName: 'South-West Bypass & Hingna Corridor',
    startJunctionId: 'J3',
    endJunctionId: 'J4',
    coordinates: [
      [21.1378, 79.0792],
      [21.1150, 79.0450],
      [21.1020, 79.0150],
    ],
    lengthKm: 6.8,
    lanes: 6,
    speedLimitKmh: 70,
    capacityVehPerHour: 3400,
    currentTrafficVeh: 1190,
    averageSpeedKmh: 54,
    utilizationPct: 35,
    congestionLevel: 'low',
    estimatedTravelTimeMin: 7.5,
    estimatedDelayMin: 1.1,
    isAlternativeRoute: true,
    status: 'underutilized',
  },
  {
    id: 'R15',
    name: 'Residency Road (Sadar Bazaar to Katol Naka)',
    code: 'NGP-RD-15',
    zone: 'Zone A',
    zoneName: 'Sitabuldi & Central Commercial',
    startJunctionId: 'J1',
    endJunctionId: 'J2',
    coordinates: [
      [21.1460, 79.0815],
      [21.1580, 79.0780],
      [21.1680, 79.0680],
    ],
    lengthKm: 3.2,
    lanes: 4,
    speedLimitKmh: 45,
    capacityVehPerHour: 1900,
    currentTrafficVeh: 1680,
    averageSpeedKmh: 19,
    utilizationPct: 88,
    congestionLevel: 'heavy',
    estimatedTravelTimeMin: 10.1,
    estimatedDelayMin: 5.8,
    status: 'congested',
  },
  {
    id: 'R16',
    name: 'Ghat Road Arterial (Cotton Market → Baidyanath Sq)',
    code: 'NGP-RD-16',
    zone: 'Zone A',
    zoneName: 'Sitabuldi & Central Commercial',
    startJunctionId: 'J2',
    endJunctionId: 'J7',
    coordinates: [
      [21.1498, 79.0832],
      [21.1420, 79.0910],
      [21.1340, 79.0980],
    ],
    lengthKm: 2.8,
    lanes: 4,
    speedLimitKmh: 40,
    capacityVehPerHour: 1800,
    currentTrafficVeh: 1720,
    averageSpeedKmh: 12,
    utilizationPct: 96,
    congestionLevel: 'severe',
    estimatedTravelTimeMin: 14.0,
    estimatedDelayMin: 9.8,
    status: 'severe' as any,
  },
  {
    id: 'R17',
    name: 'Seminary Hills & Japanese Garden Corridor',
    code: 'NGP-RD-17',
    zone: 'Zone C',
    zoneName: 'Western Institutional (Amravati-VNIT)',
    startJunctionId: 'J10',
    endJunctionId: 'J2',
    coordinates: [
      [21.1510, 79.0560],
      [21.1620, 79.0650],
      [21.1498, 79.0832],
    ],
    lengthKm: 3.9,
    lanes: 4,
    speedLimitKmh: 50,
    capacityVehPerHour: 2100,
    currentTrafficVeh: 950,
    averageSpeedKmh: 42,
    utilizationPct: 45,
    congestionLevel: 'low',
    estimatedTravelTimeMin: 5.5,
    estimatedDelayMin: 0.9,
    isAlternativeRoute: true,
    status: 'underutilized',
  },
  {
    id: 'R18',
    name: 'Mankapur Ring Road Connector',
    code: 'NGP-RD-18',
    zone: 'Zone F',
    zoneName: 'Outer Ring Road & Peripheral Bypass',
    startJunctionId: 'J10',
    endJunctionId: 'J12',
    coordinates: [
      [21.1510, 79.0560],
      [21.1750, 79.0800],
      [21.1920, 79.1020],
    ],
    lengthKm: 6.4,
    lanes: 6,
    speedLimitKmh: 75,
    capacityVehPerHour: 3600,
    currentTrafficVeh: 1420,
    averageSpeedKmh: 58,
    utilizationPct: 39,
    congestionLevel: 'low',
    estimatedTravelTimeMin: 6.6,
    estimatedDelayMin: 0.8,
    isAlternativeRoute: true,
    status: 'underutilized',
  },
  {
    id: 'R19',
    name: 'Pardi Flyover & Bhandara Road National Corridor',
    code: 'NGP-RD-19',
    zone: 'Zone F',
    zoneName: 'Outer Ring Road & Peripheral Bypass',
    startJunctionId: 'J9',
    endJunctionId: 'J8',
    coordinates: [
      [21.1485, 79.1245],
      [21.1380, 79.1350],
      [21.1235, 79.1120],
    ],
    lengthKm: 4.8,
    lanes: 6,
    speedLimitKmh: 70,
    capacityVehPerHour: 3200,
    currentTrafficVeh: 1450,
    averageSpeedKmh: 52,
    utilizationPct: 45,
    congestionLevel: 'low',
    estimatedTravelTimeMin: 5.5,
    estimatedDelayMin: 0.9,
    isAlternativeRoute: true,
    status: 'underutilized',
  },
  {
    id: 'R20',
    name: 'Southern Peripheral Expressway (MIHAN → Besa Ring Rd)',
    code: 'NGP-RD-20',
    zone: 'Zone E',
    zoneName: 'South-West Bypass & Hingna Corridor',
    startJunctionId: 'J5',
    endJunctionId: 'J4',
    coordinates: [
      [21.1098, 79.0682],
      [21.0850, 79.0750],
      [21.1275, 79.0768],
    ],
    lengthKm: 6.2,
    lanes: 6,
    speedLimitKmh: 80,
    capacityVehPerHour: 4000,
    currentTrafficVeh: 1280,
    averageSpeedKmh: 66,
    utilizationPct: 32,
    congestionLevel: 'low',
    estimatedTravelTimeMin: 5.6,
    estimatedDelayMin: 0.5,
    isAlternativeRoute: true,
    status: 'underutilized',
  },
  {
    id: 'R21',
    name: 'Futala Lake Arterial & Bharat Nagar Link',
    code: 'NGP-RD-21',
    zone: 'Zone C',
    zoneName: 'Western Institutional (Amravati-VNIT)',
    startJunctionId: 'J10',
    endJunctionId: 'J11',
    coordinates: [
      [21.1510, 79.0560],
      [21.1560, 79.0420],
      [21.1390, 79.0585],
    ],
    lengthKm: 3.5,
    lanes: 4,
    speedLimitKmh: 50,
    capacityVehPerHour: 2000,
    currentTrafficVeh: 1100,
    averageSpeedKmh: 38,
    utilizationPct: 55,
    congestionLevel: 'moderate',
    estimatedTravelTimeMin: 5.5,
    estimatedDelayMin: 1.3,
    status: 'normal',
  },
  {
    id: 'R22',
    name: 'Koradi Thermal Power Corridor (RBI Sq → Koradi)',
    code: 'NGP-RD-22',
    zone: 'Zone F',
    zoneName: 'Outer Ring Road & Peripheral Bypass',
    startJunctionId: 'J2',
    endJunctionId: 'J12',
    coordinates: [
      [21.1498, 79.0832],
      [21.1850, 79.0950],
      [21.2250, 79.1050],
    ],
    lengthKm: 7.2,
    lanes: 6,
    speedLimitKmh: 75,
    capacityVehPerHour: 3600,
    currentTrafficVeh: 1350,
    averageSpeedKmh: 60,
    utilizationPct: 37,
    congestionLevel: 'low',
    estimatedTravelTimeMin: 7.2,
    estimatedDelayMin: 0.8,
    isAlternativeRoute: true,
    status: 'underutilized',
  },
  {
    id: 'R23',
    name: 'Kalamna Wholesale Market Goods Link',
    code: 'NGP-RD-23',
    zone: 'Zone F',
    zoneName: 'Outer Ring Road & Peripheral Bypass',
    startJunctionId: 'J9',
    endJunctionId: 'J12',
    coordinates: [
      [21.1485, 79.1245],
      [21.1700, 79.1350],
      [21.1920, 79.1020],
    ],
    lengthKm: 6.5,
    lanes: 6,
    speedLimitKmh: 65,
    capacityVehPerHour: 3200,
    currentTrafficVeh: 1280,
    averageSpeedKmh: 48,
    utilizationPct: 40,
    congestionLevel: 'low',
    estimatedTravelTimeMin: 8.1,
    estimatedDelayMin: 1.2,
    isAlternativeRoute: true,
    status: 'underutilized',
  },
  {
    id: 'R24',
    name: 'Ajni Railway Overbridge & Metro Arterial',
    code: 'NGP-RD-24',
    zone: 'Zone B',
    zoneName: 'Wardha Road & MIHAN IT Corridor',
    startJunctionId: 'J6',
    endJunctionId: 'J1',
    coordinates: [
      [21.1215, 79.0850],
      [21.1340, 79.0830],
      [21.1460, 79.0815],
    ],
    lengthKm: 3.1,
    lanes: 4,
    speedLimitKmh: 45,
    capacityVehPerHour: 2000,
    currentTrafficVeh: 1940,
    averageSpeedKmh: 12,
    utilizationPct: 97,
    congestionLevel: 'severe',
    estimatedTravelTimeMin: 15.5,
    estimatedDelayMin: 11.4,
    status: 'bottleneck',
  },
];

export const initialPeakHourData: Record<'morning' | 'evening', ITrafficDataPoint[]> = {
  morning: [
    { timestamp: '09:00', timeMinutes: 0, totalVehicles: 29500, averageSpeedKmh: 32.4, averageDelayMin: 11.8, trafficDensityVehPerKm: 62, roadUtilizationPct: 60, congestedRoadsCount: 4, flowEfficiencyPct: 73 },
    { timestamp: '09:30', timeMinutes: 30, totalVehicles: 38400, averageSpeedKmh: 24.1, averageDelayMin: 18.9, trafficDensityVehPerKm: 85, roadUtilizationPct: 79, congestedRoadsCount: 8, flowEfficiencyPct: 54 },
    { timestamp: '10:00', timeMinutes: 60, totalVehicles: 46200, averageSpeedKmh: 18.4, averageDelayMin: 28.6, trafficDensityVehPerKm: 108, roadUtilizationPct: 93, congestedRoadsCount: 14, flowEfficiencyPct: 38 },
    { timestamp: '10:30', timeMinutes: 90, totalVehicles: 43800, averageSpeedKmh: 20.2, averageDelayMin: 25.1, trafficDensityVehPerKm: 101, roadUtilizationPct: 88, congestedRoadsCount: 12, flowEfficiencyPct: 44 },
    { timestamp: '11:00', timeMinutes: 120, totalVehicles: 38900, averageSpeedKmh: 24.8, averageDelayMin: 18.2, trafficDensityVehPerKm: 87, roadUtilizationPct: 78, congestedRoadsCount: 7, flowEfficiencyPct: 56 },
    { timestamp: '11:30', timeMinutes: 150, totalVehicles: 32400, averageSpeedKmh: 31.5, averageDelayMin: 12.1, trafficDensityVehPerKm: 71, roadUtilizationPct: 66, congestedRoadsCount: 4, flowEfficiencyPct: 70 },
    { timestamp: '12:00', timeMinutes: 180, totalVehicles: 27800, averageSpeedKmh: 36.2, averageDelayMin: 8.6, trafficDensityVehPerKm: 59, roadUtilizationPct: 57, congestedRoadsCount: 2, flowEfficiencyPct: 80 },
  ],
  evening: [
    { timestamp: '16:00', timeMinutes: 0, totalVehicles: 30500, averageSpeedKmh: 29.8, averageDelayMin: 14.1, trafficDensityVehPerKm: 68, roadUtilizationPct: 65, congestedRoadsCount: 5, flowEfficiencyPct: 67 },
    { timestamp: '16:30', timeMinutes: 30, totalVehicles: 39800, averageSpeedKmh: 22.8, averageDelayMin: 21.2, trafficDensityVehPerKm: 89, roadUtilizationPct: 83, congestedRoadsCount: 10, flowEfficiencyPct: 51 },
    { timestamp: '17:00', timeMinutes: 60, totalVehicles: 47900, averageSpeedKmh: 17.2, averageDelayMin: 31.2, trafficDensityVehPerKm: 114, roadUtilizationPct: 96, congestedRoadsCount: 15, flowEfficiencyPct: 36 },
    { timestamp: '17:30', timeMinutes: 90, totalVehicles: 49200, averageSpeedKmh: 16.5, averageDelayMin: 33.4, trafficDensityVehPerKm: 118, roadUtilizationPct: 98, congestedRoadsCount: 16, flowEfficiencyPct: 34 },
    { timestamp: '18:00', timeMinutes: 120, totalVehicles: 45100, averageSpeedKmh: 19.5, averageDelayMin: 26.8, trafficDensityVehPerKm: 103, roadUtilizationPct: 91, congestedRoadsCount: 13, flowEfficiencyPct: 42 },
    { timestamp: '18:30', timeMinutes: 150, totalVehicles: 37200, averageSpeedKmh: 26.5, averageDelayMin: 16.5, trafficDensityVehPerKm: 82, roadUtilizationPct: 75, congestedRoadsCount: 7, flowEfficiencyPct: 60 },
    { timestamp: '19:00', timeMinutes: 180, totalVehicles: 29200, averageSpeedKmh: 33.8, averageDelayMin: 10.2, trafficDensityVehPerKm: 63, roadUtilizationPct: 61, congestedRoadsCount: 3, flowEfficiencyPct: 75 },
  ],
};

export const initialAlerts: IAlert[] = [
  {
    id: 'alt-1',
    type: 'critical',
    title: 'Severe Wardha Road Corridor Bottleneck',
    message: 'Wardha Road Arterial (NGP-RD-01) and Central Avenue (NGP-RD-02) running at 97% capacity with average vehicular speed plummeted to 11 km/h.',
    location: 'Sitabuldi & Lokmat Square Sector',
    timestamp: '10:05 AM',
    isRead: false,
    actionRequired: 'Initiate dynamic traffic diversion to South Ring Road (NGP-RD-04) & Ambazari Bypass.',
  },
  {
    id: 'alt-2',
    type: 'warning',
    title: 'Underutilized Outer Ring Road Capacity Available',
    message: 'Nagpur Outer Ring Road (NGP-RD-03) and Wadi Bypass (NGP-RD-13) operating at only 28%–39% load. 2,400 veh/hr spare capacity available.',
    location: 'Zone F - Outer Ring Road Corridor',
    timestamp: '09:48 AM',
    isRead: false,
    actionRequired: 'Update Variable Message Signs (VMS) at Variety Sq and Law College Sq.',
  },
  {
    id: 'alt-3',
    type: 'warning',
    title: 'Severe Queue Backlog at Chhatrapati Square (J5)',
    message: 'Chhatrapati Square (J5) queue backlog reached 120 vehicles due to heavy MIHAN IT influx. Average delay 105s per vehicle.',
    location: 'J-CHT-05 (Chhatrapati Sq)',
    timestamp: '09:35 AM',
    isRead: false,
    actionRequired: 'Execute Webster Signal Auto-Optimization (+20s Green Split on North-South axis).',
  },
  {
    id: 'alt-4',
    type: 'info',
    title: 'Morning Monsoon Rain Delay on Amravati Road',
    message: 'Monsoon shower detected across Law College & VNIT zone (Zone C). Road surface friction coefficient adjusted by -14%.',
    location: 'Zone C - Western Institutional',
    timestamp: '09:15 AM',
    isRead: true,
  },
  {
    id: 'alt-5',
    type: 'success',
    title: 'Nagpur Metro Green-Wave Synchronized',
    message: 'Metro Feeder BRT along Kamptee Road operating at 89% flow efficiency with zero queue spillover.',
    location: 'Zone F - Northern Sector',
    timestamp: '09:00 AM',
    isRead: true,
  },
];

export const initialRouteAlternatives: IRouteAlternative[] = [
  {
    id: 'alt-rt-1',
    sourceName: 'Variety Square (Sitabuldi)',
    destinationName: 'Chhatrapati Square (Wardha Road)',
    currentRoute: {
      name: 'Direct Wardha Road Corridor (NGP-RD-01 → NGP-RD-05)',
      roadCodes: ['NGP-RD-01', 'NGP-RD-05'],
      distanceKm: 5.5,
      estimatedTravelTimeMin: 22.5,
      congestionLevel: 'severe',
      vehicleCount: 2280,
      delayMin: 16.6,
    },
    recommendedRoute: {
      name: 'Via Ambazari Lake Promenade & South Ring Road (NGP-RD-12 → NGP-RD-04)',
      roadCodes: ['NGP-RD-12', 'NGP-RD-04'],
      distanceKm: 6.8,
      estimatedTravelTimeMin: 7.9,
      congestionLevel: 'low',
      vehicleCount: 850,
      delayMin: 1.4,
      timeSavedMin: 14.6,
    },
    diversionPercentage: 40,
    strategyApplied: false,
  },
  {
    id: 'alt-rt-2',
    sourceName: 'Itwari & Central Avenue (J9)',
    destinationName: 'MIHAN SEZ / Airport (J5)',
    currentRoute: {
      name: 'Direct CA Road & Ghat Road (NGP-RD-02 → NGP-RD-16)',
      roadCodes: ['NGP-RD-02', 'NGP-RD-16'],
      distanceKm: 7.4,
      estimatedTravelTimeMin: 39.1,
      congestionLevel: 'severe',
      vehicleCount: 2040,
      delayMin: 28.8,
    },
    recommendedRoute: {
      name: 'Via Great Nag Road & South Ring Road Bypass (NGP-RD-06 → NGP-RD-04 → NGP-RD-20)',
      roadCodes: ['NGP-RD-06', 'NGP-RD-04', 'NGP-RD-20'],
      distanceKm: 9.2,
      estimatedTravelTimeMin: 12.8,
      congestionLevel: 'low',
      vehicleCount: 920,
      delayMin: 2.1,
      timeSavedMin: 26.3,
    },
    diversionPercentage: 45,
    strategyApplied: false,
  },
  {
    id: 'alt-rt-3',
    sourceName: 'Law College Sq (Amravati Rd)',
    destinationName: 'Automotive Square (Kamptee Rd)',
    currentRoute: {
      name: 'Direct via Sadar & Residency Road (NGP-RD-07 → NGP-RD-15 → NGP-RD-08)',
      roadCodes: ['NGP-RD-07', 'NGP-RD-15', 'NGP-RD-08'],
      distanceKm: 9.6,
      estimatedTravelTimeMin: 28.4,
      congestionLevel: 'heavy',
      vehicleCount: 1680,
      delayMin: 17.5,
    },
    recommendedRoute: {
      name: 'Via Outer Ring Road Wadi-Kamptee Bypass (NGP-RD-03 → NGP-RD-18)',
      roadCodes: ['NGP-RD-03', 'NGP-RD-18'],
      distanceKm: 11.2,
      estimatedTravelTimeMin: 11.4,
      congestionLevel: 'low',
      vehicleCount: 780,
      delayMin: 1.2,
      timeSavedMin: 17.0,
    },
    diversionPercentage: 50,
    strategyApplied: false,
  },
];
